import { type } from '@tauri-apps/plugin-os';
import i18n from '../i18n';

export const MOUSE_CLICK_KEYS = [
  'LClick',
  'RClick',
  'MClick',
]

export const IGNORE_KEY_LIST = [
  'NumLock',
  'VolumeUp',
  'VolumeDown',
]

export const MODIFIER_KEY_LIST = [
  'ControlLeft', 
  'ControlRight', 
  'AltLeft', 
  'AltRight', 
  'ShiftLeft', 
  'ShiftRight', 
  'MetaLeft', 
  'MetaRight', 
];

export const WindowsKeyLabels: Record<string, string | (() => string)> = {
  'ControlLeft': 'Ctrl',
  'ControlRight': 'Ctrl',
  'ShiftLeft': 'Shift',
  'ShiftRight': 'Shift',
  'AltLeft': 'Alt',
  'AltRight': 'Alt',
  'MetaLeft': 'Win',
  'MetaRight': 'Win',
  'Num0': '0',
  'Num1': '1',
  'Num2': '2',
  'Num3': '3',
  'Num4': '4',
  'Num5': '5',
  'Num6': '6',
  'Num7': '7',
  'Num8': '8',
  'Num9': '9',
  'Kp0': () => i18n.t('keys.kp0'),
  'Kp1': () => i18n.t('keys.kp1'),
  'Kp2': () => i18n.t('keys.kp2'),
  'Kp3': () => i18n.t('keys.kp3'),
  'Kp4': () => i18n.t('keys.kp4'),
  'Kp5': () => i18n.t('keys.kp5'),
  'Kp6': () => i18n.t('keys.kp6'),
  'Kp7': () => i18n.t('keys.kp7'),
  'Kp8': () => i18n.t('keys.kp8'),
  'Kp9': () => i18n.t('keys.kp9'),
  'KpDelete': () => i18n.t('keys.kpDelete'),
  'KpDivide': () => i18n.t('keys.kpDivide'),
  'KpMultiply': () => i18n.t('keys.kpMultiply'),
  'KpMinus': () => i18n.t('keys.kpMinus'),
  'KpPlus': () => i18n.t('keys.kpPlus'),
  'PreviousTrack': '⏮️',
  'NextTrack': '⏭️',
  'PlayPause': '⏯️',
  'Pause': '⏸️',
  'PageUp': 'PG▲',
  'PageDown': 'PG▼',
  'Escape': 'Esc',
  'Return': '↩',
  'Tab': '⇥',
  'UpArrow': '⬆',
  'DownArrow': '⬇',
  'LeftArrow': '⬅',
  'RightArrow': '➡',
  'VolumeMute': '🔇',
  'BackQuote': '`',
  'SemiColon': ';',
  'Quote': "'",
  'Comma': ',',
  'Dot': '.',
  'Slash': '/',
  'LeftBracket': '[',
  'RightBracket': ']',
  'BackSlash': '\\',
  'Minus': '-',
  'Equal': '=',
  'LClick': () => i18n.t('keys.leftClick'),
  'MClick': () => i18n.t('keys.middleClick'),
  'RClick': () => i18n.t('keys.rightClick'),
};

export const MacOSKeyLabels: Record<string, string | (() => string)> = {
  'ControlLeft': 'Ctrl',
  'ControlRight': 'Ctrl',
  'ShiftLeft': 'Shift',
  'ShiftRight': 'Shift',
  'AltLeft': '⌥',
  'AltRight': '⌥',
  'MetaLeft': '⌘',
  'MetaRight': '⌘',
  'Num0': '0',
  'Num1': '1',
  'Num2': '2',
  'Num3': '3',
  'Num4': '4',
  'Num5': '5',
  'Num6': '6',
  'Num7': '7',
  'Num8': '8',
  'Num9': '9',
  'Kp0': () => i18n.t('keys.kp0'),
  'Kp1': () => i18n.t('keys.kp1'),
  'Kp2': () => i18n.t('keys.kp2'),
  'Kp3': () => i18n.t('keys.kp3'),
  'Kp4': () => i18n.t('keys.kp4'),
  'Kp5': () => i18n.t('keys.kp5'),
  'Kp6': () => i18n.t('keys.kp6'),
  'Kp7': () => i18n.t('keys.kp7'),
  'Kp8': () => i18n.t('keys.kp8'),
  'Kp9': () => i18n.t('keys.kp9'),
  'KpDelete': () => i18n.t('keys.kpDelete'),
  'KpDivide': () => i18n.t('keys.kpDivide'),
  'KpMultiply': () => i18n.t('keys.kpMultiply'),
  'KpMinus': () => i18n.t('keys.kpMinus'),
  'KpPlus': () => i18n.t('keys.kpPlus'),
  'PreviousTrack': '⏮',
  'NextTrack': '⏭',
    'PlayPause': '⏯',
  'PageUp': 'PG▲',
  'PageDown': 'PG▼',
  'Escape': 'Esc',
  'Return': '↩',
  'Tab': '⇥',
  'UpArrow': '⬆',
  'DownArrow': '⬇',
  'LeftArrow': '⬅',
  'RightArrow': '➡',
  'VolumeMute': '🔇',
  'BackQuote': '`',
  'SemiColon': ';',
  'Quote': "'",
  'Comma': ',',
  'Dot': '.',
  'Slash': '/',
  'LeftBracket': '[',
  'RightBracket': ']',
  'BackSlash': '\\',
  'Minus': '-',
  'Equal': '=',
  'LClick': () => i18n.t('keys.leftClick'),
  'MClick': () => i18n.t('keys.middleClick'),
  'RClick': () => i18n.t('keys.rightClick'),
};

export const LinuxKeyLabels: Record<string, string | (() => string)> = {
  'ControlLeft': 'Ctrl',
  'ControlRight': 'Ctrl',
  'ShiftLeft': 'Shift',
  'ShiftRight': 'Shift',
  'AltLeft': 'Alt',
  'AltRight': 'Alt',
  'MetaLeft': 'Super',
  'MetaRight': 'Super',
  'Num0': '0',
  'Num1': '1',
  'Num2': '2',
  'Num3': '3',
  'Num4': '4',
  'Num5': '5',
  'Num6': '6',
  'Num7': '7',
  'Num8': '8',
  'Num9': '9',
  'Kp0': () => i18n.t('keys.kp0'),
  'Kp1': () => i18n.t('keys.kp1'),
  'Kp2': () => i18n.t('keys.kp2'),
  'Kp3': () => i18n.t('keys.kp3'),
  'Kp4': () => i18n.t('keys.kp4'),
  'Kp5': () => i18n.t('keys.kp5'),
  'Kp6': () => i18n.t('keys.kp6'),
  'Kp7': () => i18n.t('keys.kp7'),
  'Kp8': () => i18n.t('keys.kp8'),
  'Kp9': () => i18n.t('keys.kp9'),
  'KpDelete': () => i18n.t('keys.kpDelete'),
  'KpDivide': () => i18n.t('keys.kpDivide'),
  'KpMultiply': () => i18n.t('keys.kpMultiply'),
  'KpMinus': () => i18n.t('keys.kpMinus'),
  'KpPlus': () => i18n.t('keys.kpPlus'),
  'PreviousTrack': '⏮',
  'NextTrack': '⏭',
    'PlayPause': '⏯',
  'PageUp': 'PG▲',
  'PageDown': 'PG▼',
  'Escape': 'Esc',
  'Return': '↩',
  'Tab': '⇥',
  'UpArrow': '⬆',
  'DownArrow': '⬇',
  'LeftArrow': '⬅',
  'RightArrow': '➡',
  'VolumeMute': '🔇',
  'BackQuote': '`',
  'SemiColon': ';',
  'Quote': "'",
  'Comma': ',',
  'Dot': '.',
  'Slash': '/',
  'LeftBracket': '[',
  'RightBracket': ']',
  'BackSlash': '\\',
  'Minus': '-',
  'Equal': '=',
  'LClick': () => i18n.t('keys.leftClick'),
  'MClick': () => i18n.t('keys.middleClick'),
  'RClick': () => i18n.t('keys.rightClick'),
};

export const KeyLabel = async (key: string): Promise<string> => {
  const osType = await type();
  
  let labels: Record<string, string | (() => string)>;
  switch (osType) {
    case 'macos':
      labels = MacOSKeyLabels;
      break;
    case 'linux':
      labels = LinuxKeyLabels;
      break;
    case 'windows':
    default:
      labels = WindowsKeyLabels;
      break;
  }

  const label = labels[key];
  if (typeof label === 'function') {
    return label();
  }
  return label || key;
};
